start: "program" "main" "{" var_declaration* procedure* begin_end "}"

var_declaration: "var" IDENTIFIER ("," IDENTIFIER)* ":" type ";"
type: T_INT | T_FLOAT | T_STRING | T_CHAR | T_BOOL
T_INT: "int"
T_FLOAT: "float"
T_STRING: "string"
T_CHAR: "char"
T_BOOL: "bool"

procedure: "procedure" IDENTIFIER "{" begin_end "}"

begin_end: "begin" ";" code_block* "end" ";"
?code_block: statement ";"
          | if | while | for

?statement: write | assignment | function_call | expression
write: "write" "(" expression ")"
assignment: IDENTIFIER ("[" expression "]")? ":=" expression
function_call: IDENTIFIER "(" ")"

if: "if" "(" expression ")" "then" block ("else" block)?

while: "while" "(" expression ")" "do" block

for: "for" "(" statement ";" expression ";" statement ")" block

block: "{" code_block* "}"

?expression: additive_expression ((LT_OP | GT_OP | LTE_OP | GTE_OP | EQ_OP) additive_expression)?
?additive_expression: multiplicative_expression ((ADD_OP | SUB_OP | OR_OP) multiplicative_expression)*
?multiplicative_expression: factor ((MUL_OP | DIV_OP | MOD_OP | AND_OP) factor)*

?factor: ("not" | "-")? (constant | variable | "(" expression ")")
?variable: IDENTIFIER ("[" expression "]" | "++" | "--")?

constant: INT | FLOAT | CHAR | STRING | BOOL

// Operators
LT_OP: "<"
GT_OP: ">"
LTE_OP: "<="
GTE_OP: ">="
EQ_OP: "=="

ADD_OP: "+"
SUB_OP: "-"
OR_OP: "or"

MUL_OP: "*"
DIV_OP: "/"
MOD_OP: "%"
AND_OP: "and"

// Regex
LETTER: ("a".."z"|"A".."Z")
NUMBER: "0".."9"
IDENTIFIER: ("_"|LETTER) ("_"|LETTER|NUMBER)*

COMMON_CHARS: LETTER | NUMBER | "_" | ":" | ";" | "." | "," | "<" | ">" | "=" | "(" | ")" | "[" | "]" | "{" | "}" | "+" | "-" | "*" | "/" | "%" | "|" | "&" | "!" | "\\" | "?" | "@" | "#" | "~" | "`" | "^" | " "
ESCAPE_SEQUENCES: "\\\"" | "\\'" | "\\n" | "\\t" | "\\b" | "\\\\" | "\\0"
STRING_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "'"
CHAR_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "\""

// Types literals
INT: ("-")? NUMBER+
FLOAT: ("-")? NUMBER* "." NUMBER~1..9
STRING: "\""STRING_CHAR*"\""
CHAR: "'"CHAR_CHAR"'"
BOOL: "true" | "false"

%import common.WORD
%ignore " "
%ignore "\n"
%ignore "\t"