start: "program" "main" "{" var_declaration* procedure* begin "}"

var_declaration: "var" single_var_declaration ("," single_var_declaration)* ":" type ";"
?single_var_declaration: IDENTIFIER
!type: "int" | "float" | "string" | "char" | "bool"

procedure: "function" IDENTIFIER "(" ")" "{" begin "}"

begin: "begin" ";" code_block* "end" ";"
?code_block: statement ";"
          | if_ | while_ | for_stmt

?statement: write | assignment | function_call | expression
write: "write" "(" expression ")" | "writeln" "(" expression ")"
assignment: IDENTIFIER ":=" expression
function_call: IDENTIFIER "(" ")"

if_: "if" "(" expression ")" "then" block ("else" block)?

while_: "while" "(" expression ")" "do" block

for_stmt: "for" "(" statement ";" expression ";" statement ")" block

block: "{" code_block* "}"

?expression: relative_expression_or
?relative_expression_or: relative_expression_and (or_op relative_expression_and)*
?relative_expression_and: relative_expression (and_op relative_expression)*
?relative_expression: additive_expression (rel_op additive_expression)?
?additive_expression: multiplicative_expression (add_op multiplicative_expression)*
?multiplicative_expression: factor (mul_op factor)*

?factor: unary_operator* (constant | variable | "(" expression ")")
!unary_operator: "not" | "-"

variable: IDENTIFIER step_operator?
!step_operator: "++" | "--"
?constant: INT | FLOAT | CHAR | STRING | bool

// Operators
!rel_op: "<" | ">" | "<=" | ">=" | "==" | "!="
!add_op: "+" | "-"
!mul_op: "*" | "/" | "%"
!or_op: "or"
!and_op: "and"

// Regex
LETTER: ("a".."z"|"A".."Z")
NUMBER: "0".."9"
IDENTIFIER: ("_"|LETTER) ("_"|LETTER|NUMBER)*

COMMON_CHARS: LETTER | NUMBER | "_" | ":" | ";" | "." | "," | "<" | ">" | "=" | "(" | ")" | "[" | "]" | "{" | "}" | "+" | "-" | "*" | "/" | "%" | "|" | "&" | "!" | "\\" | "?" | "@" | "#" | "~" | "`" | "^" | " "
ALPHABET: COMMON_CHARS | "'" | "\""
ESCAPE_SEQUENCES: "\\\"" | "\\'" | "\\n" | "\\t" | "\\b" | "\\\\" | "\\0"
STRING_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "'"
CHAR_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "\""

// Types literals
INT: ("-")? NUMBER+
FLOAT: ("-")? NUMBER* "." NUMBER~1..9
STRING: "\""STRING_CHAR*"\""
CHAR: "'"CHAR_CHAR"'"
!bool: "true" | "false"

%import common.WORD
%ignore " "
%ignore "\n"
%ignore "\t"