start: "program" "main" "{" var_declaration* procedure* begin "}"

var_declaration: "var" single_var_declaration ("," single_var_declaration)* ":" type ";"
?single_var_declaration: IDENTIFIER | array_declaration
array_declaration: IDENTIFIER "[" INT "]"
!type: "int" | "float" | "string" | "char" | "bool"

procedure: "procedure" IDENTIFIER "{" begin "}"

begin: "begin" ";" code_block* "end" ";"
?code_block: statement ";"
          | if | while | for

?statement: write | assignment | function_call | expression
write: "write" "(" expression ")"
assignment: IDENTIFIER ("[" expression "]")? ":=" expression
function_call: IDENTIFIER "(" ")"

if: "if" "(" expression ")" "then" block ("else" block)?

while: "while" "(" expression ")" "do" block

for: "for" "(" statement ";" expression ";" statement ")" block

block: "{" code_block* "}"

?expression: additive_expression (rel_op additive_expression)?
?additive_expression: multiplicative_expression (add_op multiplicative_expression)*
?multiplicative_expression: factor (mul_op factor)*

?factor: ("not" | "-")? (constant | variable | "(" expression ")")

variable: IDENTIFIER array_index? (INCREMENTER | DECREMENTER)?
array_index: ("[" expression "]")
INCREMENTER: "++"
DECREMENTER: "--"
constant: INT | FLOAT | CHAR | STRING | BOOL

// Operators
!rel_op: "<" | ">" | "<=" | ">=" | "=="
!add_op: "+" | "-" | "or"
!mul_op: "*" | "/" | "%" | "and"

// Regex
LETTER: ("a".."z"|"A".."Z")
NUMBER: "0".."9"
IDENTIFIER: ("_"|LETTER) ("_"|LETTER|NUMBER)*

COMMON_CHARS: LETTER | NUMBER | "_" | ":" | ";" | "." | "," | "<" | ">" | "=" | "(" | ")" | "[" | "]" | "{" | "}" | "+" | "-" | "*" | "/" | "%" | "|" | "&" | "!" | "\\" | "?" | "@" | "#" | "~" | "`" | "^" | " "
ALPHABET: COMMON_CHARS | "'" | "\""
ESCAPE_SEQUENCES: "\\\"" | "\\'" | "\\n" | "\\t" | "\\b" | "\\\\" | "\\0"
STRING_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "'"
CHAR_CHAR: COMMON_CHARS | ESCAPE_SEQUENCES | "\""

// Types literals
INT: ("-")? NUMBER+
FLOAT: ("-")? NUMBER* "." NUMBER~1..9
STRING: "\""STRING_CHAR*"\""
CHAR: "'"CHAR_CHAR"'"
BOOL: "true" | "false"

%import common.WORD
%ignore " "
%ignore "\n"
%ignore "\t"